# Generated by Django 4.2 on 2023-04-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CiviCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
        migrations.AddField(
            model_name='vote',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CiviCore.issue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=180),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_value',
            field=models.IntegerField(choices=[(-1, 'Downvote'), (0, 'Undecided'), (1, 'Upvote')]),
        ),
    ]
